[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuração para SPAs (redireciona rotas para o index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de cabeçalhos para cache e segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 

# Configurações para os formulários Netlify
[forms]
  # Formulário de contato principal
  [forms.contact]
    name = "contact"
    [forms.contact.email]
      to = "fraancieelj@gmail.com"
      subject = "Novo contato do site Lupi Mídias"
      includeData = true
      
  # Formulário de consultoria
  [forms.consultoria]
    name = "consultoria"
    [forms.consultoria.email]
      to = "fraancieelj@gmail.com"
      subject = "Nova solicitação de consultoria - Lupi Mídias"
      includeData = true 