[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configurações para o Netlify
[build]
  publish = "dist"
  command = "npm run build"

# Configurações de cache e headers para diferentes tipos de arquivos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: *.googletagmanager.com; font-src 'self'; connect-src 'self' *.googletagmanager.com; frame-src 'self' *.googletagmanager.com; object-src 'none'"

# Cache longo para recursos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações para os formulários Netlify
[forms]
  # Formulário de contato principal
  [forms.contact]
    name = "contact"
    [forms.contact.email]
      to = "fraancieelj@gmail.com"
      subject = "Novo contato do site Lupi Mídias"
      includeData = true
      
  # Formulário de consultoria
  [forms.consultoria]
    name = "consultoria"
    [forms.consultoria.email]
      to = "fraancieelj@gmail.com"
      subject = "Nova solicitação de consultoria - Lupi Mídias"
      includeData = true

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 